#!/usr/bin/env node
// scripts/build-site.js
// Reads <target>/docs/{architecture,diagrams,setup,starter-tasks}.md and writes <target>/index.html.
// Usage:
//   node scripts/build-site.js                                  (workspace root, default title)
//   node scripts/build-site.js --target examples/jobgap --title "JobGap"
// No npm dependencies required.

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// Simple CLI args: --target <dir> --title <name> --subtitle <text>
function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const TARGET   = path.resolve(ROOT, arg('target', '.'));
const TITLE    = arg('title', 'Galaxium Travels');
const SUBTITLE = arg('subtitle', 'Generated by IBM Bob');
const DOCS_DIR = path.join(TARGET, 'docs');
const OUT      = path.join(TARGET, 'index.html');
const TEMPLATE = path.join(ROOT, 'scripts', 'template.html');

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── Ordered tab definitions ────────────────────────────────────────────────
const TABS = [
  { key: 'architecture', file: 'architecture.md'  },
  { key: 'diagrams',     file: 'diagrams.md'       },
  { key: 'setup',        file: 'setup.md'          },
  { key: 'tasks',        file: 'starter-tasks.md'  },
];

// ── Escape a raw markdown string for embedding in a JS template literal ───
// Escapes: backticks, backslashes, and ${ sequences.
function escapeForTemplateLiteral(str) {
  return str
    .replace(/\\/g, '\\\\')       // \ → \\  (must be first)
    .replace(/`/g, '\\`')         // ` → \`
    .replace(/\$\{/g, '\\${');    // ${ → \${
}

// ── Build the DOCS block that replaces {{DOCS_BLOCK}} in the template ─────
function buildDocsBlock() {
  const lines = ['const DOCS = {};', ''];
  for (const { key, file } of TABS) {
    const src = path.join(DOCS_DIR, file);
    if (!fs.existsSync(src)) {
      console.error(`ERROR: missing ${src}`);
      process.exit(1);
    }
    const raw     = fs.readFileSync(src, 'utf8');
    const escaped = escapeForTemplateLiteral(raw);
    lines.push(`DOCS.${key} = \`${escaped}\`;`, '');
  }
  return lines.join('\n');
}

// ── Main ───────────────────────────────────────────────────────────────────
const tmpl = fs.readFileSync(TEMPLATE, 'utf8');

const PLACEHOLDER = '{{DOCS_BLOCK}}';
if (!tmpl.includes(PLACEHOLDER)) {
  console.error(`ERROR: template.html does not contain the placeholder "${PLACEHOLDER}"`);
  process.exit(1);
}

const output = tmpl
  .replace(PLACEHOLDER, () => buildDocsBlock())
  .split('{{PROJECT_NAME}}').join(escapeHtml(TITLE))
  .split('{{FOOTER_NOTE}}').join(escapeHtml(SUBTITLE));
fs.writeFileSync(OUT, output, 'utf8');

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
console.log(`✓ ${path.relative(ROOT, OUT) || 'index.html'} written (${kb} KB)`);